name: Node.js
version: 0.3.2
description: Runtime for Node.js applications
license: Apache-2.0
language: nodejs
maintainers:
  - name: Sam Roberts
    email: vieuxtech@gmail.com
    github-id: sam-github
default-template: simple
