apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: {{.nameSuffix}}
  namespace: {{.namespace}}
spec:
  serviceAccount: {{.serviceAccount}}
  timeout: 
  pipelineRef:
    name: {{.collectionID}}-image-retag-push-pipeline
  resources:
    - name: docker-src-image
      resourceRef:
        name: docker-src-{{.nameSuffix}}
    - name: docker-dest-image
      resourceRef:
        name: docker-dest-{{.nameSuffix}}
